---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-helloworld-app
  name: demo-helloworld
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: demo-helloworld-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: demo-helloworld-app
  name: demo-helloworld-depl
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo-helloworld-app
  template:
    metadata:
      labels:
        app: demo-helloworld-app
    spec:
      containers:
        - image: ghcr.io/phpengine/helloworld:latest
          imagePullPolicy: Always
          name: demo-helloworld
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

