---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vqcomm-vservice
  name: vqcomm-helloworld
  namespace: corpwebsites
spec:
  type: ClusterIP
  selector:
    app: vqcomm-vservice
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: vqcomm-helloworld
#  name: vqcomm-helloworld-np
#  namespace: corpwebsites
#spec:
#  type: NodePort
#  selector:
#   app: vqcomm-helloworld
#  ports:
#    - name: http
#      protocol: TCP
#      nodePort: 30222
#      port: 80
#      targetPort: 80
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: nginx-to-helloworld-ingress
#  namespace: corpwebsites
#spec:
#  ingressClassName: public
#  selector:
#    app: vqcomm-helloworld
#  rules:
#  - host: nginx-to-helloworld.doubleingress.dev
#    http:
#      paths:
#      - backend:
#          service:
#            name: vqcomm-helloworld
#            port:
#              number: 80
#        path: /
#        pathType: Prefix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: vqcomm-vservice
  name: vqcomm-helloworld-depl
  namespace: corpwebsites
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vqcomm-vservice
  template:
    metadata:
      labels:
        app: vqcomm-vservice
    spec:
      containers:
        - image: ghcr.io/phpengine/helloworld:latest
          imagePullPolicy: Always
          name: vqcomm-helloworld
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

