---
apiVersion: v1
kind: Namespace
metadata:
  name: fables-wordpress
---
apiVersion: v1
kind: Namespace
metadata:
  name: fables-api
---
apiVersion: v1
kind: Namespace
metadata:
  name: fables-games
---
apiVersion: v1
kind: Namespace
metadata:
  name: corpwebsites