---

- name: Display URL For Helloworld Nodeport
  debug:
    msg: |
      HA Proxy URL : http://{{ server_hostname }}:30222
      NGinx URL : http://{{ server_hostname }}:30222
      Istio URL : http://{{ server_hostname }}:30222
      Non Ingress URL : http://{{ server_hostname }}:30222
