---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vqcomm-vservice
  name: vqcomm-vservice-np
  namespace: corpwebsites
spec:
  type: NodePort
  selector:
    app: vqcomm-vservice
  ports:
    - name: http
      protocol: TCP
      nodePort: 30100
      port: 80
      targetPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-to-helloworld-gateway
spec:
  selector:
    app: vqcomm-vservice
    istio: ingressgateway
  servers:
  - hosts:
      - "gw-istio-to-helloworld.doubleingress.dev"
    port:
      number: 30100
      name: http
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: vqcomm-vservice
  name: istio-to-helloworld-vservice
spec:
  hosts:
  - "gw-istio-to-helloworld.doubleingress.dev"
  gateways:
  - istio-to-helloworld-gateway
  http:
  - route:
    - destination:
        host: vqcomm-helloworld
        port:
          number: 80