---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-vservice
  name: demo-vservice-np
  namespace: default
spec:
  type: NodePort
  selector:
    app: demo-vservice
  ports:
    - name: http
      protocol: TCP
      nodePort: 30100
      port: 80
      targetPort: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-to-helloworld-gateway
spec:
  selector:
    app: demo-vservice
    istio: ingressgateway
  servers:
  - hosts:
      - "{{ server_hostname }}"
    port:
      number: 30100
      name: http
      protocol: HTTP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: demo-vservice
  name: istio-to-helloworld-vservice
spec:
  hosts:
  - "{{ server_hostname }}"
  gateways:
  - istio-to-helloworld-gateway
  http:
  - route:
    - destination:
        host: demo-helloworld
        port:
          number: 80