---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: istio
spec:
  controller: istio.io/ingress-controller
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-helloworld
  name: demo-istio-np
  namespace: default
spec:
  type: NodePort
  selector:
    app: demo-helloworld
  ports:
    - name: http
      protocol: TCP
      nodePort: 30200
      port: 80
      targetPort: 80
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: istio-to-helloworld
  namespace: default
spec:
  ingressClassName: istio
  selector:
    app: demo-helloworld
  rules:
  - host: "{{ server_hostname }}"
    http:
      paths:
      - backend:
          service:
            name: demo-helloworld
            port:
              name: http
        path: /
        pathType: Prefix
  - host: "istio.{{ server_hostname }}"
    http:
      paths:
      - backend:
          service:
            name: demo-helloworld
            port:
              name: http
        path: /
        pathType: Prefix

