---

- name: Ensure Manifests directory
  shell: |
    mkdir -p /opt/kubes-manifests/
    mkdir -p /opt/kubes-manifests/corpwebsites

- name: Copy manifests
  template:
    src: "{{ item }}"
    dest: "/opt/kubes-manifests/{{ item }}"
  with_items: "{{ app_manifests }}"

- name: Create a Deployment by reading the definition from a local file
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: default
    context: "{{ k8s_context }}"
    state: present
    src: "/opt/kubes-manifests/{{ item }}"
  with_items: "{{ app_manifests }}"
  retries: 3
  delay: 10
