---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: haproxy-to-istio
  namespace: default
  annotations:
    haproxy-ingress.github.io/forwardfor: "add"
    haproxy-ingress.github.io/backend-protocol: "h2"
    haproxy-ingress.github.io/secure-backends: "false"
spec:
  ingressClassName: haproxy
  defaultBackend:
    service:
      name: istio-ingressgateway
      port:
        name: http2
  rules:
  - host: "{{ server_hostname }}"
    http:
      paths:
      - backend:
          service:
            name: istio-ingressgateway
            port:
              name: http2
        path: /
        pathType: Prefix
  - host: "haproxy.{{ server_hostname }}"
    http:
      paths:
      - backend:
          service:
            name: istio-ingressgateway
            port:
              name: http2
        path: /
        pathType: Prefix