---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-to-helloworld
  namespace: default
  annotations:
    compute-full-forwarded-for: "true"
    use-forwarded-headers: "true"
spec:
  ingressClassName: public
  defaultBackend:
    service:
      name: demo-helloworld
      port:
        name: http
  rules:
  - host: "{{ server_hostname }}"
    http:
      paths:
      - backend:
          service:
            name: demo-helloworld
            port:
              name: http
        path: /
        pathType: Prefix
  - host: "nginx.{{ server_hostname }}"
    http:
      paths:
      - backend:
          service:
            name: demo-helloworld
            port:
              name: http
        path: /
        pathType: Prefix
