---

- name: Ensure Manifests directory
  shell: mkdir -p /opt/kubes-manifests/

- name: Template over manifests
  template:
    src: "templates/ingress-haproxy.yml"
    dest: "/opt/kubes-manifests/ingress-haproxy.yml"

- name: Apply haproxy ingress def from file
  shell: "/usr/local/bin/kubectl apply -f /opt/kubes-manifests/ingress-haproxy.yml --validate=false"
  become: true
  retries: 30
  delay: 10

#- name: Restart RKE2 Server
#  ansible.builtin.service:
#    name: "rke2-server"
#    state: restarted