---

- name: Ensure Manifests directory
  shell: mkdir -p /opt/kubes-manifests/

- name: Template over manifests
  template:
    src: "templates/{{ item }}"
    dest: "/opt/kubes-manifests/{{ item }}"
  with_items:
    - "ingress-haproxy-to-helloworld.yml"
#    - "ingress-haproxy-to-istio.yml"

- name: Apply haproxy ingress def from file
  shell: "{{ kubectl_command }} apply -f /opt/kubes-manifests/{{ item }} --validate=false"
  become: true
  retries: 30
  delay: 10
  with_items:
    - "ingress-haproxy-to-helloworld.yml"
#    - "ingress-haproxy-to-istio.yml"
