---

- name: Ensure Manifests directory
  shell: mkdir -p /opt/kubes-manifests/

- name: Copy manifests
  template:
    src: "templates/{{ item }}"
    dest: "/opt/kubes-manifests/{{ item }}"
  with_items:
    - ingress-nginx-to-helloworld.yml
#    - ingress-nginx-to-istio.yml

- name: Create a Deployment by reading the definition from a local file
  kubernetes.core.k8s:
    kubeconfig: ~/.kube/config
    namespace: default
    context: "{{ k8s_context }}"
    state: present
    src: "/opt/kubes-manifests/{{ item }}"
  with_items:
    - ingress-nginx-to-helloworld.yml
#    - ingress-nginx-to-istio.yml
